id: 66865b17d4a944e7bfa9c6cf4a3d67fc
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_70-The_Sutra_of_the_Question_of_Subahu-v1
  language: bo
  author: ''
  volume: {}
